### PR TITLE
firstBreak & time0Cor: minor changes

### PR DESCRIPTION
**Pull request by guifh**
See comments with commits.

### CODE REVIEW

**Comment by emanuelhuber** [comment]
And you can split the long warnings such that their are not longer than 80 characters, e.g.,
`warning("this is a very very very ",
                 "long warning.\n",
                 "I'm now starting a new",
                 " line with \\n.")`

**Comment by emanuelhuber** [comment]
It’s good to insert break line in the warning. The warning is easier to read when it is compact.

**Comment by emanuelhuber** [comment]
I started a 'contributing' file, such that the code is coherently build. I will add a short 'coding style' section:

https://github.com/emanuelhuber/RGPR/blob/master/CONTRIBUTING.md

**Comment by guifh** [comment]
Well, when the warning is issued in R, the text will be adjusted to the size of your window anyways... I can create new lines but it can also look awkward depending on your window/screen size... I am going to cancel this pull request and create a new one with corrections...

**Pull request closed without merging**
